# Generated by Django 4.0.3 on 2022-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_content_question_token_alter_lesson_uuid_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
