# Generated by Django 4.0.3 on 2022-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_question_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_submitted',
        ),
        migrations.AlterField(
            model_name='content',
            name='media',
            field=models.FileField(upload_to=''),
        ),
    ]
