# Generated by Django 4.0.3 on 2022-04-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_submission_is_submitted_alter_content_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='lesson.lesson'),
        ),
    ]
