# Generated by Django 4.0.3 on 2022-04-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_content_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lesson.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='lesson.submission'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='lesson.content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lesson.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='lesson.token'),
        ),
    ]
